/**
 * Demo: typed i18n with generated type bindings.
 *
 * Run: npx tsx projectTest/i18n/demo-typed.tsx
 *
 * The typed bindings in ./typed/ were generated by:
 *   npx ink-kit makeLanguageType projectTest/i18n/locales projectTest/i18n/typed --watch
 *
 * The typed `t()` and `useI18n()` provide:
 *  - IDE autocompletion for TranslationKey
 *  - Compile-time errors for invalid keys
 *  - Type-safe interpolation params (string | number)
 */
import React, { useState } from 'react';
import { render, Box, Text, useInput } from 'ink';
import { LanguageProvider } from '../../src/index.js';
import { t, useI18n } from './typed/i18n.js';

/** Options object param type used by the typed t(). */
interface TParams {
  level?: string | number;
  score?: string | number;
  age?: string | number;
  count?: string | number;
}

function TypedI18nDemo() {
  const { setLanguage, getLanguages, currentLanguage } = useI18n();
  const [langIdx, setLangIdx] = useState(0);

  useInput((input, key) => {
    if (key.escape || input === 'q') process.exit(0);
    if (input === 'l') {
      const langs = getLanguages();
      const next = (langIdx + 1) % langs.length;
      setLangIdx(next);
      setLanguage(langs[next]);
    }
  });

  return (
    <Box flexDirection="column" paddingY={1}>
      <Text bold color="cyan">
        {/*
         * TypeScript knows "title" is a valid TranslationKey.
         * Typing t('titl') would be a compile error ✨
         */}
        {t('title')}
      </Text>

      <Box marginTop={1} flexDirection="column">
        {/*
         * TypeScript checks that params match TranslationParams['game.info'].
         * { level: string | number; score: string | number }
         * Passing { level: 3 } without 'score' is a compile error.
         */}
        <Text>  {t('game.info', { params: { level: 3, score: 4200 } })}</Text>
        <Text>  {t('player', { params: { age: 25 } })}</Text>
        <Text>  {t('inventory', { params: { count: 7 } })}</Text>
      </Box>

      <Box marginTop={2}>
        <Text dimColor>
          Language: {currentLanguage}  [L] Switch ({getLanguages().join(', ')})  [Q] Quit
        </Text>
      </Box>
    </Box>
  );
}

render(
  <LanguageProvider
    path="./projectTest/i18n/locales"
    defaultLanguage="en-US"
  >
    <TypedI18nDemo />
  </LanguageProvider>,
);
