// Auto-generated by ink-kit makeLanguageType.
// Do not edit manually.

export type TranslationKey =
  | 'game.back'
  | 'game.info'
  | 'inventory'
  | 'play'
  | 'player'
  | 'quit'
  | 'settings'
  | 'title';

export type TranslationParams = {
  'game.back': undefined;
  'game.info': {
    level: string | number;
    score: string | number;
  };
  'inventory': {
    count: string | number;
  };
  'play': undefined;
  'player': {
    age: string | number;
  };
  'quit': undefined;
  'settings': undefined;
  'title': undefined;
};
