// Auto-generated by ink-kit makeLanguageType.
// Do not edit manually.

import { t as rawT, useI18n as rawUseI18n } from '../../src/index.js';
import type { TranslationKey, TranslationParams } from './i18n-types.js';

/**
 * Typed translation function. Drop-in replacement for the original `t`.
 *
 * @param key - A translation key shared by all language files.
 * @param options - Optional params and/or context.
 */
export function t<K extends TranslationKey>(
  key: K,
  options?: { params?: TranslationParams[K]; context?: string },
): string {
  return rawT(key, options as any);
}

/**
 * Typed `useI18n` hook. Returns the same API as the original hook but
 * with a type-safe `t` function.
 */
export function useI18n(): Omit<ReturnType<typeof rawUseI18n>, 't'> & { t: typeof t } {
  const ctx = rawUseI18n();
  return { ...ctx, t: (key: any, options?: any) => ctx.t(key, options) };
}
